/**
 * Русские переводы встроенных текстов PrimeNG (FR-001, NFR-004).
 *
 * NFR-004 требует 100 % русских текстов интерфейса; единственное
 * исключение — подписи кнопок подтверждающих диалогов «Yes»/«No»
 * (дословно, FR-014/FR-017), поэтому accept/reject намеренно оставлены
 * без перевода.
 */
import { Translation } from 'primeng/api';

export const PRIME_NG_RU: Translation = {
  // Подтверждающие диалоги: единственное англоязычное исключение NFR-004.
  accept: 'Yes',
  reject: 'No',

  // Кнопки и общие подписи.
  clear: 'Очистить',
  apply: 'Применить',
  choose: 'Выбрать',
  upload: 'Загрузить',
  cancel: 'Отмена',
  pending: 'В ожидании',
  today: 'Сегодня',
  completed: 'Завершено',

  // Сообщения о пустых данных, поиске и выбранных файлах.
  emptyMessage: 'Записей нет',
  emptyFilterMessage: 'Ничего не найдено',
  emptySearchMessage: 'Ничего не найдено',
  emptySelectionMessage: 'Ничего не выбрано',
  searchMessage: 'Доступно результатов: {0}',
  selectionMessage: 'Выбрано элементов: {0}',
  noFileChosenMessage: 'Файл не выбран',
  fileChosenMessage: 'Выбрано файлов: {0}',
  fileSizeTypes: ['Б', 'КБ', 'МБ', 'ГБ', 'ТБ', 'ПБ', 'ЭБ', 'ЗБ', 'ЙБ'],

  // Операторы и правила фильтрации таблиц.
  startsWith: 'Начинается с',
  contains: 'Содержит',
  notContains: 'Не содержит',
  endsWith: 'Заканчивается на',
  equals: 'Равно',
  notEquals: 'Не равно',
  noFilter: 'Без фильтра',
  lt: 'Меньше',
  lte: 'Меньше или равно',
  gt: 'Больше',
  gte: 'Больше или равно',
  is: 'Равно',
  isNot: 'Не равно',
  before: 'До',
  after: 'После',
  dateIs: 'Дата равна',
  dateIsNot: 'Дата не равна',
  dateBefore: 'Дата раньше',
  dateAfter: 'Дата позже',
  matchAll: 'Совпадают все',
  matchAny: 'Совпадает любой',
  addRule: 'Добавить правило',
  removeRule: 'Удалить правило',

  // Календарь (p-datepicker); формат дат на экранах — дд.мм.гггг (NFR-004).
  dayNames: [
    'воскресенье',
    'понедельник',
    'вторник',
    'среда',
    'четверг',
    'пятница',
    'суббота',
  ],
  dayNamesShort: ['вс', 'пн', 'вт', 'ср', 'чт', 'пт', 'сб'],
  dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  monthNames: [
    'Январь',
    'Февраль',
    'Март',
    'Апрель',
    'Май',
    'Июнь',
    'Июль',
    'Август',
    'Сентябрь',
    'Октябрь',
    'Ноябрь',
    'Декабрь',
  ],
  monthNamesShort: [
    'Янв',
    'Фев',
    'Мар',
    'Апр',
    'Май',
    'Июн',
    'Июл',
    'Авг',
    'Сен',
    'Окт',
    'Ноя',
    'Дек',
  ],
  dateFormat: 'dd.mm.yyyy',
  firstDayOfWeek: 1,
  weekHeader: 'Н',
  chooseYear: 'Выбрать год',
  chooseMonth: 'Выбрать месяц',
  chooseDate: 'Выбрать дату',
  prevDecade: 'Предыдущее десятилетие',
  nextDecade: 'Следующее десятилетие',
  prevYear: 'Предыдущий год',
  nextYear: 'Следующий год',
  prevMonth: 'Предыдущий месяц',
  nextMonth: 'Следующий месяц',
  prevHour: 'Предыдущий час',
  nextHour: 'Следующий час',
  prevMinute: 'Предыдущая минута',
  nextMinute: 'Следующая минута',
  prevSecond: 'Предыдущая секунда',
  nextSecond: 'Следующая секунда',
  am: 'AM',
  pm: 'PM',

  // Индикатор надёжности пароля.
  passwordPrompt: 'Введите пароль',
  weak: 'Слабый',
  medium: 'Средний',
  strong: 'Надёжный',

  // ARIA-подписи для вспомогательных технологий.
  aria: {
    close: 'Закрыть',
    previous: 'Предыдущий',
    next: 'Следующий',
    navigation: 'Навигация',
    scrollTop: 'Наверх',
    pageLabel: 'Страница {page}',
    firstPageLabel: 'Первая страница',
    lastPageLabel: 'Последняя страница',
    nextPageLabel: 'Следующая страница',
    prevPageLabel: 'Предыдущая страница',
    previousPageLabel: 'Предыдущая страница',
    rowsPerPageLabel: 'Строк на странице',
    jumpToPageDropdownLabel: 'Перейти к странице',
    jumpToPageInputLabel: 'Номер страницы',
    selectAll: 'Выбрать все',
    unselectAll: 'Снять выделение',
    selectRow: 'Выбрать строку',
    unselectRow: 'Отменить выбор строки',
    expandRow: 'Развернуть строку',
    collapseRow: 'Свернуть строку',
    showFilterMenu: 'Показать меню фильтра',
    hideFilterMenu: 'Скрыть меню фильтра',
    filterOperator: 'Оператор фильтра',
    filterConstraint: 'Условие фильтра',
    listView: 'Список',
    gridView: 'Плитка',
    star: 'Одна звезда',
    stars: 'Звёзд: {n}',
    zoomImage: 'Увеличить изображение',
    zoomIn: 'Приблизить',
    zoomOut: 'Отдалить',
    rotateRight: 'Повернуть вправо',
    rotateLeft: 'Повернуть влево',
    removeLabel: 'Удалить',
    browseFiles: 'Обзор файлов',
    maximizeLabel: 'Развернуть',
  },
};
